INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (1, '123 Main St', 'Los Angeles', 'CA', '90001');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (2, '456 Oak Ave', 'Long Beach', 'CA', '90802');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (3, '789 Pine Blvd', 'Pasadena', 'CA', '91101');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (4, '101 Broadway St', 'Santa Monica', 'CA', '90401');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (5, '202 Sunset Rd', 'Glendale', 'CA', '91201');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (6, '303 Elm Ln', 'Burbank', 'CA', '91501');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (7, '444 Jay St', 'Van Nuys', 'CA', '91401');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (8, '212 First Ln', 'Pasadena', 'CA', '91101');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (9, '424 Hollywood Blvd', 'Hollywood', 'CA', '91311');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (10, '500 Wonderland Ln', 'Los Angeles', 'CA', '90078');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (11, '158 Palm Ave', 'Los Angeles', 'CA', '91444');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (12, '137 Third St', 'Glendale', 'CA', '92345');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (13, '222 Celestial Ln', 'Santa Monica', 'CA', '90412');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (14, '333 Cosmic Ct', 'Burbank', 'CA', '91501');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (15, '555 Normal St', 'Long Beach', 'CA', '90002');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (16, '567 Astro Blvd', 'Hollywood', 'CA', '91313');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (17, '988 Melrose Blvd', 'Hollywood', 'CA', '92100');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (18, '777 Lucky Ln', 'Van Nuys', 'CA', '91404');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (19, '789 Nebula Blvd', 'Long Beach', 'CA', '90000');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (20, '888 Los Angeles Ave', 'Los Angeles', 'CA', '90090');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (21, '999 Enchanted Ln', 'Burbank', 'CA', '91515');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (22, '210 Beverly Hills Blvd', 'Beverly Hills', 'CA' '90210');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (23, '543 Long Beach Blvd', 'Long Beach', 'CA', '90802');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (24, '765 Pasadena Plaza', 'Pasadena', 'CA', '91101');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (25, '876 Whittier Way', 'Whittier', 'CA', '90601');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (26, '915 Echo Park Ave', 'Los Angeles', 'CA', '90012');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (27, '280 Watts Way', 'Watts', 'CA', '90001');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (28, '654 Culver City Ln', 'Culver City', 'CA', '90230');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (29, '987 Malibu Road', 'Malibu', 'CA', '90265');
INSERT INTO [$(Address)]([UserID],[Street_Address],[City],[State],[Zip_Code]) VALUES (30, '845 Inglewood Blvd', 'Inglewood', 'CA', '90301');