INSERT INTO [$(UserArea)] VALUES (1,4,1);
INSERT INTO [$(UserArea)] VALUES (2,1,2);
INSERT INTO [$(UserArea)] VALUES (3,3,3);
INSERT INTO [$(UserArea)] VALUES (4,1,4);
INSERT INTO [$(UserArea)] VALUES (5,3,5);
INSERT INTO [$(UserArea)] VALUES (6,2,6);
INSERT INTO [$(UserArea)] VALUES (7,4,7);

INSERT INTO [$(UserArea)] VALUES (8,4,8);
INSERT INTO [$(UserArea)] VALUES (9,4,9);
INSERT INTO [$(UserArea)] VALUES (10,4,10);
INSERT INTO [$(UserArea)] VALUES (11,4,11);
INSERT INTO [$(UserArea)] VALUES (12,1,12);
INSERT INTO [$(UserArea)] VALUES (13,1,13);
INSERT INTO [$(UserArea)] VALUES (14,1,14);
INSERT INTO [$(UserArea)] VALUES (15,1,15);
INSERT INTO [$(UserArea)] VALUES (16,2,16);
INSERT INTO [$(UserArea)] VALUES (17,2,17);
INSERT INTO [$(UserArea)] VALUES (18,2,18);
INSERT INTO [$(UserArea)] VALUES (19,2,19);
INSERT INTO [$(UserArea)] VALUES (20,3,20);
INSERT INTO [$(UserArea)] VALUES (21,3,21);
INSERT INTO [$(UserArea)] VALUES (22,3,22);
INSERT INTO [$(UserArea)] VALUES (23,3,23);
INSERT INTO [$(UserArea)] VALUES (24,1,24);
INSERT INTO [$(UserArea)] VALUES (25,2,25);
INSERT INTO [$(UserArea)] VALUES (26,3,26);






