INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Jerry','Yan','JerryY@gmail.com','manager',false, 'https://images.generated.photos/hhD046j0oSUxEUbhH3aRYZtrRDgTiKibm926XCmUCSc/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/OTU5MjE2LmpwZw.jpg',false, 2, 'Bachelor',true, '2023/12/24 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Alice','Johnson','AliceJ@gmail.com','password123',false, 'https://images.generated.photos/fWqbA_jZjgJQC-hmk4skHf97vfD9TvtWdP-ad5Hzw7A/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MTk5OTAwLmpwZw.jpg',false, 1, 'Associate',true, '2023/12/23 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Bob','Smith','BobS@gmail.com','securepass',false, 'https://images.generated.photos/yqnjUXlOXNtpe9faSCqGBfKOPgN2SqucKZo8lRSAmpA/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjY3NDczLmpwZw.jpg',false, 2, 'Bachelor',true, '2023/12/27 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('David','Miller','DavidM@gmail.com','pass1234',true, 'image',false, 1, 'Associate',false, '2023/12/26 12:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('John','Williams','JohnW@gmail.com','johnpass',false, 'image',false, 2, 'Bachelor',true, '2023/12/29 15:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Tom','Johnson','TomJ@gmail.com','tompass',false, 'image',false, 1, 'Associate',true, '2023/12/31 09:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Alice','Jones','AliceJ@gmail.com','pass123',false, 'image',true, 1, 'Bachelor',false, '2024/11/22 10:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('William','Turner','WilliamT@gmail.com','willpass',true, 'image',false, 2, 'Bachelor',true, '2024/12/10 14:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Olivia','Brown','OliviaB@gmail.com','oliviapass',false, 'image',true, 1, 'Associate',false, '2024/09/28 11:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Daniel','Wilson','DanielW@gmail.com','danielpass',true, 'image',false, 3, 'Bachelor',true, '2024/10/20 13:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Ava','Miller','AvaM@gmail.com','avapass',false, 'image',true, 2, 'Bachelor',false, '2024/12/05 10:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Mia','Martin','MiaM@gmail.com','miapass',false, 'image',true, 1, 'Associate',false, '2024/12/15 14:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('David','Moore','DavidM@gmail.com','davidpass',true, 'image',false, 3, 'Associate',true, '2024/12/01 11:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Sophie','Adams','SophieA@gmail.com','sophiepass',false, 'image',true, 3, 'Associate',false, '2024/12/22 10:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Matthew','Cooper','MatthewC@gmail.com','mattpass',true, 'image',false, 3, 'Bachelor',true, '2024/12/03 14:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Avery','Wright','AveryW@gmail.com','averypass',false, 'image',true, 3, 'Associate',false, '2024/12/17 11:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Logan','Baker','LoganB@gmail.com','loganpass',true, 'image',false, 1, 'Associate',true, '2024/12/29 13:00:00');



INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Michael','Davis','MichaelD@gmail.com','myp@ss123',false, 'https://images.generated.photos/0w1qv8kT4uzhHXIAZritV-YsRxPqJ3iATPSNgfbdsuw/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/OTE0NDY3LmpwZw.jpg',false, 9, 'Masters',true, '2023/12/24 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Sophie','Turner','SophieT@gmail.com','secure1234',false, 'https://images.generated.photos/luxNDYgbLWwAov3T--19NfJEsJoWSSJFDB9MThfHqt4/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NDIzMTg1LmpwZw.jpg',false, 9, 'Masters',true, '2023/12/27 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('John','Doe','JohnD@gmail.com','johnspass',false, 'https://images.generated.photos/ddcXlc8JE8QZmRMVe7mqSfv09NociVkvmu-XWskQaKE/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjU5OTU4LmpwZw.jpg',false, 9, 'Bachelor',true, '2023/12/23 13:30:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Emily','Clark','EmilyC@gmail.com','strongpass',true, 'image',false, 9, 'Master',true, '2023/12/25 14:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Linda','Anderson','LindaA@gmail.com','lindapass',true, 'image',false, 9, 'PhD',true, '2023/12/28 11:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Sophie','Martin','SophieM@gmail.com','sophiepass',true, 'image',false, 9, 'Master',false, '2023/12/30 10:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) values ('Emma','Turner','EmmaT@gmail.com','emmapass',true, 'image',false, 9, 'PhD',false, '2024/01/01 13:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Michael','Smith','MichaelS@gmail.com','securepass',true, 'image',false, 9, 'Master',true, '2024/10/15 12:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Sophia','Davis','SophiaD@gmail.com','sophiapass',false, 'image',true, 9, 'PhD',false, '2024/11/30 09:00:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Christopher','Harris','ChristopherH@gmail.com','chrispass',true, 'image',false, 9, 'PhD',true, '2024/11/18 12:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Ella','Russell','EllaR@gmail.com','ellapass',false, 'image',true, 9, 'PhD',false, '2024/12/12 12:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('James','Jackson','JamesJ@gmail.com','jamespass',true, 'image',false, 9, 'PhD',true, '2024/11/25 13:15:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('Emma','White','EmmaW@gmail.com','emmapass',false, 'image',true, 9, 'Master',false, '2024/12/08 09:45:00');
INSERT INTO [$(User)]([FirstName],[LastName],[Email],[Password],[OngoingMentorship],[Image],[Identity],[Degree],[Availability]) VALUES ('James','Jackson','JamesJ@gmail.com','jamespass',true, 'image',false, 9, 'PhD',true, '2024/11/25 13:15:00');


