// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTD_Mentorship_Project.Models;

public partial class Area
{
    public int AreaId { get; set; }

    public string AreaName { get; set; }

    public virtual ICollection<UserArea> UserArea { get; set; } = new List<UserArea>();
}