// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTD_Mentorship_Project.Models;

public partial class FieldOfWork
{
    public int FieldOfWorkId { get; set; }

    public string FieldOfWorkName { get; set; }
}