// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTD_Mentorship_Project.Models;

public partial class Identity
{
    public int Id { get; set; }

    public string IdentityName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}