// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTD_Mentorship_Project.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool OngoingMentorship { get; set; }

    public string Image { get; set; }

    public int IdentityId { get; set; }

    public string Degree { get; set; }

    public DateTime? Availability { get; set; }
    public ICollection<Address> Addresses { get; set; }

    public virtual Identity Identity { get; set; }

    public virtual ICollection<MentorMentee> MentorMenteeMentees { get; set; } = new List<MentorMentee>();

    public virtual ICollection<MentorMentee> MentorMenteeMentors { get; set; } = new List<MentorMentee>();

    public virtual ICollection<UserArea> UserAreas { get; set; } = new List<UserArea>();

    //Added required fieilds

    public string Company { get; set; }
    public string  FieldofWork { get; set; }
    public string DOB { get; set; }
    public string State { get; set; }
    public string  City{ get; set; }

    public string Zip { get; set; }

    public string SelectedUserTypeId { get; set; }
}