// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTD_Mentorship_Project.Models;

public partial class UserArea
{
    public int UserAreaId { get; set; }

    public int AreaId { get; set; }

    public int UserId { get; set; }

    public virtual Area Area { get; set; }

    public virtual User User { get; set; }
}